### ISSUE TITLE
Missing requirements.txt?

### ISSUE THREAD

**Issue by DebbyX3** [jianzongwu/Language-Driven-Video-Inpainting#4]
Hello! 
I would like to try your work as a part of a potential new paper. However, I'm stuck while setting up the project. 

Everything is fine until I try to install the dependencies of the `requirements.txt` file, which does not exist in the repo. 
Am I doing something wrong and you are referring to another `requirements.txt` file? 
Currently, I skipped this step and just installed the next packages you suggest, and trying to reverse-engineer the missing packages

Thanks! :)

(On Ubuntu  22.04 4 LTS)

**Comment by jianzongwu** [comment]
Thanks for the reminder! I have uploaded the `requirements.txt` file to this repo.

**Comment by DebbyX3** [comment]
Thank you! I'll try again in the next few days :)

**Comment by DebbyX3** [comment]
Now, the installation works as expected, but I have the same problem addressed in Issue #5. 
I'm going to close this and comment on the other :)
