### ISSUE TITLE
Inpainting with mask?

### ISSUE THREAD

**Issue by longyangqi** [jianzongwu/Language-Driven-Video-Inpainting#7]
Could we use this model on the video inpainting task with masks?

Thanks!

**Comment by jianzongwu** [comment]
Hello. The LGVI model is for language-driven video inpainting, which takes language input as guidance for the removal areas. If you intend to perform the video inpainting task with masks, you can check other repos, like [https://github.com/geekyutao/Inpaint-Anything](https://github.com/geekyutao/Inpaint-Anything)
